name: hairdresser_project
description: "A new Flutter project." 

publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: ^3.5.3
package_info_plus: ^4.0.0 
dependencies:
  flutter:
    sdk: flutter
 
  go_router: ^14.2.3
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  iconsax_flutter: ^1.0.0
  curved_navigation_bar: ^1.0.6
  get: ^4.6.6
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.0.0+2
  video_player: ^2.9.2  
  chewie: ^1.8.5
  flutter_staggered_grid_view: ^0.7.0
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

flutter:
 
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
           

  assets:
    - assets/icon_image/barbershop.png
    - assets/icon_image/appointment_outlined.png
    - assets/icon_image/appointment.png
    - assets/icon_image/barbershop_outlined.png
    - assets/icon_image/placemarker.png
    - assets/images/sun.jpg
    - assets/images/waterfall.jpeg
    - assets/videos/video.mp4
    - assets/images/boy.jpg
    - assets/images/hairdresser.jpg